version: '3.7'

services:
  app:
    image: openjdk:11
    container_name: springboot-app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://switchyard.proxy.rlwy.net:21349/railway?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=uvpofOvasFblInHEynOsPGqanAXMhodT
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379

  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"
