version: '3.7'
services:
  app:
    image: openjdk:11
    container_name: springboot-app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
      - redis
    environment:
      - SPRING_DATASOURCE_URL=mysql://root:RMxQwJLgbGQpWqBxIhSiAhzrpJYczAqd@nozomi.proxy.rlwy.net:42692/railway
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=RMxQwJLgbGQpWqBxIhSiAhzrpJYczAqd
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379

  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=forum_language
    ports:
      - "3306:3306"

  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"